In [1]:
import numpy as np
import pandas as pd

In [2]:
def evaluate(submission,groundtruth):
    ap_sum = 0.0
    first_pred_acc_sum = 0.0
    counter = 0
    for sub, tru in zip(submission, groundtruth):
        if len(sub) != len(tru):
            raise Exception('Line {} should contain {} predictions, but instead contains '
                            '{}'.format(counter+1,len(tru),len(sub)))
        ap_sum += ave_pre(sub,tru,counter)
        first_pred_acc_sum += sub[0] == tru[0]
        counter+=1
    ap = ap_sum/counter
    first_pred_acc = first_pred_acc_sum/counter
    return ap,first_pred_acc
def ave_pre(submission,groundtruth,counter):
    s = 0.0
    t = 0.0
    c = 1.0
    for x, y in zip(submission, groundtruth):
        if x != 0 and x != 1:
            raise Exception('Invalid prediction in line {}, should be 0 or 1'.format(counter))
        if x==y:
            s += 1.0
            t += s / c
        c += 1
    return t/len(groundtruth)

In [3]:
l = 10
tmp = [
    ave_pre(
        [1 for _ in range(l)],
        [0 if i==j else 1 for j in range(l)],
        None)
    for i in range(l)]
tmp = 1 - np.array(tmp)
tmp * l / np.sum(tmp)

array([1.7157535 , 1.42285967, 1.22759711, 1.08115019, 0.96399265,
       0.86636138, 0.78267742, 0.70945396, 0.64436644, 0.58578768])

In [4]:
l = 9
tmp = [
    ave_pre(
        [1 for _ in range(l)],
        [0 if i==j else 1 for j in range(l)],
        None)
    for i in range(l)]
tmp = 1 - np.array(tmp)
tmp * l / np.sum(tmp)

array([1.6782454 , 1.38162748, 1.18388219, 1.03557323, 0.91692605,
       0.81805341, 0.73330543, 0.65915095, 0.59323586])

In [5]:
l = 8
tmp = [
    ave_pre(
        [1 for _ in range(l)],
        [0 if i==j else 1 for j in range(l)],
        None)
    for i in range(l)]
tmp = 1 - np.array(tmp)
tmp * l / np.sum(tmp)

array([1.63699919, 1.33584297, 1.13507215, 0.98449404, 0.86403155,
       0.76364614, 0.67760151, 0.60231245])

In [6]:
l = 7
tmp = [
    ave_pre(
        [1 for _ in range(l)],
        [0 if i==j else 1 for j in range(l)],
        None)
    for i in range(l)]
tmp = 1 - np.array(tmp)
tmp * l / np.sum(tmp)

array([1.59110833, 1.28428303, 1.07973283, 0.92632018, 0.80359006,
       0.70131497, 0.61365059])

In [7]:
l = 6
tmp = [
    ave_pre(
        [1 for _ in range(l)],
        [0 if i==j else 1 for j in range(l)],
        None)
    for i in range(l)]
tmp = 1 - np.array(tmp)
tmp * l / np.sum(tmp)

array([1.53926702, 1.22513089, 1.01570681, 0.85863874, 0.73298429,
       0.62827225])

In [8]:
l = 5
tmp = [
    ave_pre(
        [1 for _ in range(l)],
        [0 if i==j else 1 for j in range(l)],
        None)
    for i in range(l)]
tmp = 1 - np.array(tmp)
tmp * l / np.sum(tmp)

array([1.47948164, 1.15550756, 0.93952484, 0.7775378 , 0.64794816])